version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - api
    ports:
      - "80:80"
    depends_on:
      - db

  api:
    container_name: api
    build:
      args:
        user: api
        uid: 1000
      context: ./lumen/
      dockerfile: Dockerfile
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    links:
      - db:db
    depends_on:
      - db